databases:
  - name: model_deploy
    plan: free
    databaseName: model_deploy
    user: model_deploy

services:
  - type: web
    plan: free
    name: model_deploy
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn model_deploy.asgi:application -k uvicorn.workers.UvicornWorker --worker-class gevent"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: model_deploy
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4